import { Trip } from "./types";

export const kashmirTrip: Trip = {
  name: "Kashmir & Katra",
  destination: "Srinagar · Gulmarg · Pahalgam · Katra",
  start_date: "2026-05-17",
  end_date: "2026-05-25",
  group_size: 8,
  organizer: "Trip Makers",
  driver: {
    name: "Mr. Zaid",
    phone: "+917889529789",
    vehicle_number: "JK 04 H 5338",
    vehicle_type: "AC Tempo Traveller",
  },
  hotels: [
    { name: "Hotel Asian Park", location: "Srinagar", phone: "+919424728320", check_in: "2026-05-17", check_out: "2026-05-19", room_type: "Deluxe", meal_plan: "B&D", address: "Residency Rd, Srinagar, J&K 190001", wifi_name: "AsianPark_Guest", wifi_password: "Kashmir2026" },
    { name: "Hotel Mama Palace", location: "Gulmarg", phone: "+919906000241", check_in: "2026-05-19", check_out: "2026-05-20", room_type: "Deluxe", meal_plan: "B&D", address: "Main Gulmarg Rd, Gulmarg, J&K 193403", wifi_name: "MamaPalace_WiFi", wifi_password: "Gulmarg@123" },
    { name: "Cheerful Charley Houseboat", location: "Dal Lake, Srinagar", phone: "+919906849134", check_in: "2026-05-20", check_out: "2026-05-21", room_type: "Deluxe", meal_plan: "B&D", address: "Dal Lake Nagin, Srinagar, J&K 190001", wifi_name: "CheerfulCharley", wifi_password: "DalLake#1" },
    { name: "Hotel Srichan Resort", location: "Pahalgam", phone: "+919622430888", check_in: "2026-05-21", check_out: "2026-05-23", room_type: "Deluxe", meal_plan: "B&D", address: "Pahalgam Main Rd, Pahalgam, J&K 192126", wifi_name: "Srichan_Resort", wifi_password: "Pahalgam2026" },
    { name: "Hotel Mahesh Residency", location: "Katra", phone: "+919906024084", check_in: "2026-05-23", check_out: "2026-05-25", room_type: "Deluxe", meal_plan: "B&D", address: "Bank Colony, Katra, J&K 182301", wifi_name: "MaheshResidency", wifi_password: "Vaishno@786" },
  ],
  flights: [
    {
      type: "onward",
      number: "6E 7259 + 6E 6409",
      pnr: "B417MY",
      airline: "IndiGo",
      from: "IXU Aurangabad",
      to: "SXR Srinagar",
      departure: "08:30",
      arrival: "15:05",
      date: "2026-05-17",
      via: "HYD",
      travelClass: "Economy",
      baggage: { checkin: "15 kg / person", cabin: "7 kg / person" },
      pdfUrl: "/tickets/onward-flight-B417MY.pdf",
      bookingRef: "AF27DD1006",
      legs: [
        { number: "6E 7259", from: "IXU Aurangabad", fromTerminal: "Chikkalthana Airport", to: "HYD Hyderabad", toTerminal: "Rajiv Gandhi Intl Airport", departure: "08:30", arrival: "09:55", layoverMinutes: 140 },
        { number: "6E 6409", from: "HYD Hyderabad", fromTerminal: "Rajiv Gandhi Intl Airport", to: "SXR Srinagar", toTerminal: "Srinagar Airport", departure: "12:15", arrival: "15:05" },
      ],
      passengers: [
        "Mrs. Asha Hukumchand Sharma (Adult)",
        "Mrs. Simabai Mukesh Jangid (Adult)",
        "Ms. Bhakti Mukesh Jangid (Adult)",
        "Mr. Mukesh Ramniwas Jangid (Adult)",
        "Ms. Oshin Pavan Jangid (Adult)",
        "Mrs. Jaya Omprakash Sharma (Adult)",
        "Mr. Pavan Tarachand Jangid (Adult)",
        "Miss Aasheen Pavan Jangid (Child)",
      ],
    },
    {
      type: "return",
      number: "6E 2356 + 6E 6256",
      pnr: "L2KZSB",
      bookingRef: "AO260417744",
      airline: "IndiGo",
      from: "IXJ Jammu",
      to: "IXU Aurangabad",
      departure: "13:10",
      arrival: "20:50",
      date: "2026-05-25",
      via: "DEL",
      travelClass: "Economy",
      baggage: { checkin: "15 kg / person", cabin: "7 kg / person" },
      pdfUrl: "/tickets/return-flight-L2KZSB.pdf",
      legs: [
        { number: "6E 2356", from: "IXJ Jammu", fromTerminal: "T1 Satwari", to: "DEL New Delhi", toTerminal: "T2 IGI", departure: "13:10", arrival: "14:35", layoverMinutes: 275 },
        { number: "6E 6256", from: "DEL New Delhi", fromTerminal: "T1 IGI", to: "IXU Aurangabad", toTerminal: "Aurangabad Airport", departure: "19:10", arrival: "20:50" },
      ],
      passengers: [
        "Mrs. Asha Hukumchand Sharma",
        "Mrs. Simabai Mukesh Jangid",
        "Mrs. Bhakti Mukesh Jangid",
        "Mr. Mukesh Ramniwas Jangid",
        "Ms. Oshin Pavan Jangid",
        "Mrs. Jaya Omprakash Sharma",
        "Mr. Pavan Tarachand Jangid",
        "Ms. Aasheen Pavan Jangid",
      ],
    },
  ],
  itinerary: [
    { day: 1, date: "2026-05-17", title: "Srinagar arrival + local sightseeing", description: "Nishat Garden · Shalimar Garden · Chashmah Shahi · Pari Mahal · Shankaracharya · Dargah Hazratbal" },
    { day: 2, date: "2026-05-18", title: "Sonmarg day trip", description: "Thajwas Glacier · Zojila Zero Point (80 km, ~2 hrs each way)" },
    { day: 3, date: "2026-05-19", title: "Srinagar → Gulmarg", description: "Scenic beauty + Gondola ride (tickets pre-booked, afternoon slot)" },
    { day: 4, date: "2026-05-20", title: "Gulmarg → Srinagar Houseboat", description: "Personal shopping + 1-hour Shikara ride on Dal Lake" },
    { day: 5, date: "2026-05-21", title: "Srinagar → Pahalgam", description: "Apple Valley · Saffron Valley · Baisaran · Mini Switzerland (horses on own cost)" },
    { day: 6, date: "2026-05-22", title: "Pahalgam local sightseeing", description: "Aru Valley · Betab Valley · Chandanwadi (by local car)" },
    { day: 7, date: "2026-05-23", title: "Pahalgam → Katra", description: "~208 km, 4–5 hrs drive · Rest at hotel" },
    { day: 8, date: "2026-05-24", title: "Vaishno Devi darshan", description: "By foot or pony (own cost)" },
    { day: 9, date: "2026-05-25", title: "Jammu drop + departure", description: "IXJ → DEL → IXU · Flight 6E 2356 at 13:10" },
  ],
  contacts: [
    { name: "Ms. Komal Surana", role: "Operations Manager", phone: "+918484899748" },
    { name: "Mr. Kshitij Runwal", role: "Emergency Contact", phone: "+919834209128" },
    { name: "Mr. Sanjay Runwal", role: "Emergency Contact", phone: "+919404544946" },
    { name: "Trip Makers Office", role: "General Enquiries", phone: "+917248984612" },
  ],
  tickets: [
    {
      activity: "Gulmarg Gondola Phase 1 & 2",
      date: "2026-05-19",
      slot: "Afternoon (12:00 PM – 3:30 PM)",
      passengers: [
        { name: "Pavan Tarachand", ticket: "463976" },
        { name: "Oshin Pavan", ticket: "463961" },
        { name: "Aasheen Pavan", ticket: "463965" },
        { name: "Mukesh Ramniwas", ticket: "463949" },
        { name: "Bhakti Mukesh", ticket: "463941" },
        { name: "Simabai", ticket: "463939" },
        { name: "Jaya Omprakash", ticket: "463971" },
        { name: "Asha Hukumchand", ticket: "463932" },
      ],
    },
  ],
};
