import { Trip } from "./types";

export const kashmirTrip: Trip = {
  name: "Kashmir & Katra",
  destination: "Srinagar · Gulmarg · Pahalgam · Katra",
  start_date: "2026-05-17",
  end_date: "2026-05-25",
  group_size: 8,
  organizer: "Trip Makers",
  operator: {
    name: "Trip Makers",
    tagline: "Crafting memories since 2018",
    logo: "🧭",
    color: "#E35A00",
    phone: "+91 98765 43210",
    website: "tripmakers.in",
  },
  driver: {
    name: "Mr. Zaid",
    phone: "+917889529789",
    vehicle_number: "JK 04 H 5338",
    vehicle_type: "AC Tempo Traveller",
  },
  hotels: [
    { name: "Hotel Asian Park", location: "Srinagar", phone: "+919424728320", check_in: "2026-05-17", check_out: "2026-05-19", room_type: "Deluxe", meal_plan: "B&D", address: "Residency Rd, Srinagar, J&K 190001", wifi_name: "AsianPark_Guest", wifi_password: "Kashmir2026", image: "https://picsum.photos/id/164/700/300" },
    { name: "Hotel Mama Palace", location: "Gulmarg", phone: "+919906000241", check_in: "2026-05-19", check_out: "2026-05-20", room_type: "Deluxe", meal_plan: "B&D", address: "Main Gulmarg Rd, Gulmarg, J&K 193403", wifi_name: "MamaPalace_WiFi", wifi_password: "Gulmarg@123", image: "https://picsum.photos/id/280/700/300" },
    { name: "Cheerful Charley Houseboat", location: "Dal Lake, Srinagar", phone: "+919906849134", check_in: "2026-05-20", check_out: "2026-05-21", room_type: "Deluxe", meal_plan: "B&D", address: "Dal Lake Nagin, Srinagar, J&K 190001", wifi_name: "CheerfulCharley", wifi_password: "DalLake#1", image: "https://picsum.photos/id/15/700/300" },
    { name: "Hotel Srichan Resort", location: "Pahalgam", phone: "+919622430888", check_in: "2026-05-21", check_out: "2026-05-23", room_type: "Deluxe", meal_plan: "B&D", address: "Pahalgam Main Rd, Pahalgam, J&K 192126", wifi_name: "Srichan_Resort", wifi_password: "Pahalgam2026", image: "https://picsum.photos/id/431/700/300" },
    { name: "Hotel Mahesh Residency", location: "Katra", phone: "+919906024084", check_in: "2026-05-23", check_out: "2026-05-25", room_type: "Deluxe", meal_plan: "B&D", address: "Bank Colony, Katra, J&K 182301", wifi_name: "MaheshResidency", wifi_password: "Vaishno@786", image: "https://picsum.photos/id/225/700/300" },
  ],
  passes: [
    {
      id: "flight-onward",
      type: "flight",
      subtype: "onward",
      title: "IXU → SXR",
      from: "IXU Aurangabad",
      to: "SXR Srinagar",
      via: "HYD",
      departure: "08:30",
      arrival: "15:05",
      date: "2026-05-17",
      reference: "B417MY",
      operator: "IndiGo",
      flightNumber: "6E 7259 + 6E 6409",
      travelClass: "Economy",
      baggage: { checkin: "15 kg / person", cabin: "7 kg / person" },
      pdfUrl: "/tickets/onward-flight-B417MY.pdf",
      passengers: [
        "Mrs. Asha Hukumchand Sharma (Adult)",
        "Mrs. Simabai Mukesh Jangid (Adult)",
        "Ms. Bhakti Mukesh Jangid (Adult)",
        "Mr. Mukesh Ramniwas Jangid (Adult)",
        "Ms. Oshin Pavan Jangid (Adult)",
        "Mrs. Jaya Omprakash Sharma (Adult)",
        "Mr. Pavan Tarachand Jangid (Adult)",
        "Miss Aasheen Pavan Jangid (Child)",
      ],
      legs: [
        { number: "6E 7259", from: "IXU Aurangabad", fromTerminal: "Chikkalthana Airport", to: "HYD Hyderabad", toTerminal: "Rajiv Gandhi Intl Airport", departure: "08:30", arrival: "09:55", layoverMinutes: 140 },
        { number: "6E 6409", from: "HYD Hyderabad", fromTerminal: "Rajiv Gandhi Intl Airport", to: "SXR Srinagar", toTerminal: "Srinagar Airport", departure: "12:15", arrival: "15:05" },
      ],
    },
    {
      id: "flight-return",
      type: "flight",
      subtype: "return",
      title: "IXJ → IXU",
      from: "IXJ Jammu",
      to: "IXU Aurangabad",
      via: "DEL",
      departure: "13:10",
      arrival: "20:50",
      date: "2026-05-25",
      reference: "L2KZSB",
      operator: "IndiGo",
      flightNumber: "6E 2356 + 6E 6256",
      travelClass: "Economy",
      baggage: { checkin: "15 kg / person", cabin: "7 kg / person" },
      pdfUrl: "/tickets/return-flight-L2KZSB.pdf",
      passengers: [
        "Mrs. Asha Hukumchand Sharma",
        "Mrs. Simabai Mukesh Jangid",
        "Mrs. Bhakti Mukesh Jangid",
        "Mr. Mukesh Ramniwas Jangid",
        "Ms. Oshin Pavan Jangid",
        "Mrs. Jaya Omprakash Sharma",
        "Mr. Pavan Tarachand Jangid",
        "Ms. Aasheen Pavan Jangid",
      ],
      legs: [
        { number: "6E 2356", from: "IXJ Jammu", fromTerminal: "T1 Satwari", to: "DEL New Delhi", toTerminal: "T2 IGI", departure: "13:10", arrival: "14:35", layoverMinutes: 275 },
        { number: "6E 6256", from: "DEL New Delhi", fromTerminal: "T1 IGI", to: "IXU Aurangabad", toTerminal: "Aurangabad Airport", departure: "19:10", arrival: "20:50" },
      ],
    },
    {
      id: "gondola",
      type: "activity",
      title: "Gulmarg Gondola Phase 1 & 2",
      date: "2026-05-19",
      reference: "GONDOLA-2026",
      slot: "Afternoon (12:00 PM – 3:30 PM)",
      activityPassengers: [
        { name: "Pavan Tarachand", ticket: "463976" },
        { name: "Oshin Pavan", ticket: "463961" },
        { name: "Aasheen Pavan", ticket: "463965" },
        { name: "Mukesh Ramniwas", ticket: "463949" },
        { name: "Bhakti Mukesh", ticket: "463941" },
        { name: "Simabai", ticket: "463939" },
        { name: "Jaya Omprakash", ticket: "463971" },
        { name: "Asha Hukumchand", ticket: "463932" },
      ],
    },
  ],
  itinerary: [
    {
      day: 0, date: "2026-05-16", title: "Departure from Aurangabad",
      description: "Reach Aurangabad Airport (IXU) by 6:30 AM. Flight 6E 7259 departs at 08:30 → Hyderabad (HYD) · Layover 2h 20m · Flight 6E 6409 departs 12:15 → lands Srinagar (SXR) at 15:05.",
      transport: "✈️ IXU Aurangabad → HYD → SXR Srinagar · IndiGo · PNR B417MY",
    },
    {
      day: 1, date: "2026-05-17", title: "Srinagar — local sightseeing",
      description: "Land at Srinagar Airport at 15:05. Driver Mr. Zaid will receive you. Evening sightseeing: Nishat Garden · Shalimar Garden · Chashmah Shahi · Shankaracharya Temple · Dargah Hazratbal.",
      transport: "🚐 Airport pickup by Mr. Zaid (JK 04 H 5338)",
    },
    {
      day: 2, date: "2026-05-18", title: "Sonmarg day trip",
      description: "Full day excursion to Sonmarg (~80 km, ~2 hrs). Thajwas Glacier · Zoji La Zero Point · Sindh River. Return to Srinagar hotel by evening.",
      transport: "🚐 Day trip from Srinagar — depart by 7:00 AM",
    },
    {
      day: 3, date: "2026-05-19", title: "Srinagar → Gulmarg",
      description: "Check out from Hotel Asian Park. Drive to Gulmarg (~56 km, ~1.5 hrs). Gondola Phase 1 & 2 pre-booked for afternoon slot (12:00 PM – 3:30 PM). Check in to Hotel Mama Palace.",
      transport: "🚐 Srinagar → Gulmarg · ~56 km · 1.5 hrs",
      included: ["Gulmarg Gondola Phase 1 & 2 tickets (pre-booked)"],
    },
    {
      day: 4, date: "2026-05-20", title: "Gulmarg → Dal Lake Houseboat",
      description: "Check out from Hotel Mama Palace. Drive back to Srinagar. Personal shopping at Lal Chowk. 1-hour Shikara ride on Dal Lake (included). Check in to Cheerful Charley Houseboat on Nagin Lake.",
      transport: "🚐 Gulmarg → Srinagar · ~56 km · 1.5 hrs",
      included: ["1-hour Shikara ride on Dal Lake"],
    },
    {
      day: 5, date: "2026-05-21", title: "Houseboat → Pahalgam",
      description: "Check out from houseboat. Drive to Pahalgam (~95 km, ~2.5 hrs) via Saffron Valley. Visit Baisaran (Mini Switzerland) — horse ride on own cost. Apple Valley · Aru Valley en route.",
      transport: "🚐 Srinagar → Pahalgam · ~95 km · 2.5 hrs",
    },
    {
      day: 6, date: "2026-05-22", title: "Pahalgam — full day",
      description: "Full day sightseeing around Pahalgam. Aru Valley · Betab Valley · Chandanwadi — covered by local taxi (own cost, approx ₹1,200–1,500 per cab). Evening leisure at Lidder River.",
      transport: "🚕 Local taxi for valley trips (own cost ~₹1,200–1,500)",
    },
    {
      day: 7, date: "2026-05-23", title: "Pahalgam → Katra",
      description: "Check out from Hotel Srichan Resort. Long drive to Katra (~208 km, 4–5 hrs). Rest at hotel. Collect Vaishno Devi yatra slip from registration counter near hotel (200 m).",
      transport: "🚐 Pahalgam → Katra · ~208 km · 4–5 hrs",
    },
    {
      day: 8, date: "2026-05-24", title: "Vaishno Devi darshan",
      description: "Early start — trek 14 km uphill to Vaishno Devi shrine. Banganga → Ardhkuwari → Bhawan. Pony/helicopter available on own cost. Return by evening. Last night in Katra.",
      transport: "🚶 14 km trek · Pony/helicopter on own cost",
    },
    {
      day: 9, date: "2026-05-25", title: "Katra → Jammu → Home",
      description: "Check out from hotel. Drive to Jammu Airport (IXJ, ~48 km, ~1 hr). Flight 6E 2356 departs Jammu at 13:10 → Delhi (DEL) · Layover · Flight 6E 6256 departs 19:10 → lands Aurangabad (IXU) at 20:50. Trip ends. 🙏",
      transport: "🚐 Katra → IXJ Jammu · ~48 km · 1 hr · then ✈️ IXJ → DEL → IXU · PNR L2KZSB",
    },
  ],
  contacts: [
    { name: "Ms. Komal Surana", role: "Operations Manager", phone: "+918484899748" },
    { name: "Mr. Kshitij Runwal", role: "Emergency Contact", phone: "+919834209128" },
    { name: "Mr. Sanjay Runwal", role: "Emergency Contact", phone: "+919404544946" },
    { name: "Trip Makers Office", role: "General Enquiries", phone: "+917248984612" },
  ],
  documents: [
    { id: "doc1", name: "Trip Itinerary PDF", type: "itinerary", emoji: "📋", url: "" },
    { id: "doc2", name: "Travel Insurance Policy", type: "insurance", emoji: "🛡️", url: "" },
    { id: "doc3", name: "Inner Line Permit — J&K", type: "permit", emoji: "📜", url: "" },
  ],
  inclusions: [
    "2 nights stay at Srinagar + 1 night Gulmarg + 1 night Houseboat + 2 nights Pahalgam + 2 nights Katra",
    "3 rooms + 1 extra mattress + 1 child no-bed on complimentary basis",
    "Breakfast & Dinner daily (except breakfast on Day 1 and dinner on last day)",
    "All transfers by AC 12-seater Tempo Traveller as per itinerary",
    "All vehicle-related expenses included",
    "All transfers & sightseeing as per itinerary",
  ],
  exclusions: [
    "5% GST (Goods & Services Tax)",
    "Entry fees at tourist places",
    "Visits other than the itinerary or repeat visits",
    "Personal expenses — room service, alcoholic & non-alcoholic beverages",
    "Porter charges, camera charges & guide charges",
    "Tips, drinks, laundry etc.",
    "Travel insurance / medical insurance",
    "International / domestic airfare or train fare (unless specified)",
  ],
  notes: [
    "Gondola tickets must be booked in advance — operator will assist",
    "Houseboat stay is on Dal Lake; carry warm clothes even in May",
    "Vehicle operates point-to-point only, not on disposal basis",
    "Carry a valid photo ID for all members at all times",
  ],
};
